### ISSUE TITLE
并发数目输入框

### ISSUE THREAD

**Issue by mybdye** [axipo/TrafficBlackhole#1]
[![tutieshi_640x422_7s.gif](http://mjjzp.cf/img/2022/02/24/c2a76e059ad2d.gif)](http://mjjzp.cf/img/2022/02/24/c2a76e059ad2d.gif)

**Comment by axipo** [comment]
@mybdye 
[感谢反馈，已修复](https://github.com/axipo/TrafficBlackhole/commit/6b96dc1bf972ad62e48e2cdfe10ac46602da456e)
